# Generated by Django 6.0 on 2025-12-27 04:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activityexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityExport',
            new_name='ActivityExportModel',
        ),
    ]
