# Generated by Django 6.0 on 2025-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_rename_activityexport_activityexportmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityexportmodel',
            name='activity_ids',
            field=models.TextField(blank=True, default=list),
        ),
    ]
